# Generated by Django 2.0.7 on 2022-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='price',
        ),
        migrations.AddField(
            model_name='patient',
            name='summary',
            field=models.TextField(default='Electric Call Bell'),
        ),
    ]
