# Generated by Django 2.0.7 on 2022-03-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20220301_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
                ('priority', models.IntegerField(default=1)),
                ('staff', models.CharField(max_length=10)),
                ('emergency', models.CharField(max_length=5)),
                ('room_number', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
